### ISSUE TITLE
Meerdere gebruikers aan groepen toevoegen in 1 keer

### ISSUE THREAD

**Issue by usserwoutV2** [SELab-2/UGent-6#231]
In frontend heb ik nu iets gemaakt dat een course admin de groepen zelf kan verdelen. Om te vermijden dat ik een groot aantal POST requests moet uitvoeren zou het handig zijn om 1 PUT request te maken om alle groepen van een cluster te overschrijven. Ik bewaar de state van alle groepen in de frontend als volgt:
```ts
type GroupCluster = {
  [groupId:string]: number[] // userIds
}
```
Dus bv:
```json
{
 "1": [1,2,3,4],
 "2": [],
 "3": [5]
}
``` 
Als het gemakkelijker is om dit op een andere manier door te geven aan de backend, dan kan ik dit nog veranderen. 

<img width="732" alt="Scherm­afbeelding 2024-04-28 om 14 24 41" src="https://github.com/SELab-2/UGent-6/assets/159531937/e0262000-a6ed-41a3-a0da-f366f0a2ca75">

**Comment by arnedierick** [comment]
Ik denk dat dit inderdaad een nuttige issue is die volgens mij niet zo moeilijk is om te implementeren in de backend. Ik begin eraan
