### ISSUE TITLE
Extra submission status

### ISSUE THREAD

**Issue by usserwoutV2** [SELab-2/UGent-6#237]
Ik dacht dat @Aqua-sc eens gezegd  had  dat er een extra submission status moet komen (de status wanneer dat een submission bezig is met testen). Ik ben niet zeker of we dit nog steeds gaan doen.

**Comment by Aqua-sc** [comment]
Dit is inderdaad iets dat we nog steeds van plan zijn. Normaal is @TR1VER bijna klaar met dit toevoegen aan de backend. Wanneer de PR daarvan gemerged is zal ik zorgen dat hier de nodige informatie komt zodat dit ook aan de frontend kan toegevoegd worden

**Comment by badduck32** [comment]
@ mij wanneer dat klaar is zodat ik dan de frontend van de submission correct kan aanpassen
