### ISSUE TITLE
App icon 

### ISSUE THREAD

**Issue by usserwoutV2** [SELab-2/UGent-6#242]
App icon (nodig omdat browsers altijd een icon in hun tab lijst tonen, momenteel is dit de default react app icon)

**Comment by arnedierick** [comment]
Dit is mijn ontwerp: 
![flavicon_arne16x16](https://github.com/SELab-2/UGent-6/assets/159790994/cca7dc39-5092-4c0d-b4dd-26263fc8ca0c)
![flavicon_arne32x32](https://github.com/SELab-2/UGent-6/assets/159790994/1d40a980-8217-4063-96b9-9df686ddae58)
