### ISSUE TITLE
APIdog updaten

### ISSUE THREAD

**Issue by usserwoutV2** [SELab-2/UGent-6#246]
Er zijn een aantal dingen aangepast aan de API. Het is dus best dat alle GET requests nog eens nagekeken worden.

**Comment by Aqua-sc** [comment]
Kdenk dat het eigenlijk wel goed zou zijn als echt alles eens nagekeken worden, ook bij de posts/patch/put request bv. voorwaarden schrijven waar de request aan moeten voldoen etc. Opzich is dit iets wat ik wel zie zitten om te doen aangezien ik wel een goed overzicht hierover heb (maar zou dan wel pas een ong. een week voor de deadline zijn  dus als iemand dit eerder zou willen doen mag dat gerust en dan kan ik het gewoon eens na)
