### ISSUE TITLE
Admins kunnen geen groepen joinen

### ISSUE THREAD

**Issue by usserwoutV2** [SELab-2/UGent-6#250]
Als je een admin rol hebt en je zit in een vak als enrolled, dan kan je niet een groep joinen. Een simpele fix is om ook course admins toe te laten om een groep te joinen, ik zie niet direct een reden waarom dit niet zou mogen. 

![Scherm­afbeelding 2024-05-05 om 22 57 20](https://github.com/SELab-2/UGent-6/assets/159531937/1cf6dabf-0d4e-467d-b7c4-ae0ef7c9a35b)
![Scherm­afbeelding 2024-05-05 om 22 57 43](https://github.com/SELab-2/UGent-6/assets/159531937/e7f788cd-3e62-4e35-93d5-c3f3d518b73a)
<img width="691" alt="Scherm­afbeelding 2024-05-05 om 22 57 54" src="https://github.com/SELab-2/UGent-6/assets/159531937/93ca8c40-5212-4b33-a4c5-00ae1d40c966">

**Comment by Aqua-sc** [comment]
Wat voor nut zou het hebben voor een admin om een groep te joinen?

**Comment by usserwoutV2** [comment]
Veel nut heeft het inderdaad niet, misschien om submission te testen? Ik geef liever course admins te veel permissies dan te weinig.

**Comment by Aqua-sc** [comment]
Ik snap u punt van liever te veel dan te weinig maar kdenk dat het hier gwn verwarrend gaat worden. Da een admin submissions moet kunnen testen ga ik wel mee akkoord maar ik zou een manier zoeken dat dit kan zonder dat hij in een groep zit (ev. aparte route)

**Comment by usserwoutV2** [comment]
Bedoel je verwarrend om te implementeren of verwarrend dat je als course admin een groep mag joinen?

**Comment by Aqua-sc** [comment]
Kdenk gewoon zo voor plaatsen waar alle groepen samen komen bv. de progressie van een project wordt een groep die door de prof gemaakt&gejoined zou zijn om indiening te testen  daar ook invoor en dat soort dingen. Daarom dat ik liever een aparte manier voorzie en dan kunnen wij en de gebruikers er op andere plekken vanuit gaan dat de groepen gwn voor studenten zijn

**Comment by Aqua-sc** [comment]
@usserwoutV2 mijn idee hiervoor momenteel is om indien een course_admin een submission doet dit op te slaan zonder groep id. Ik zou dan ook een aparte route toevoegen `/api/projects/{projectId}/adminsubmissions` die dan al de submissions van een admin teruggeeft. Lijkt dit oké en iets wat dan nog aan de frontend kan toegevoegd worden?

**Comment by usserwoutV2** [comment]
Is zeker mogelijk.
